void main() {
  try {
    throw RangeError('RangeError');
  } catch (e) {
    print('aa');
  }
}
